#!/bin/sh
#
# Auto connect bluetooth controllers
#

systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"

case "$1" in
  start)
        enabled="`$systemsetting  -command load -key controllers.bluetooth.enabled`"
        if [ "$enabled" == "1" ];then
                echo "Starting Bluetooth"
                start-stop-daemon -S -q -p /var/run/bluetoothcontrollers.pid --exec /recalbox/scripts/bluetoothcontrollers.sh
                start-stop-daemon -S -q -p /var/run/bluetoothd.pid --exec /usr/libexec/bluetooth/bluetoothd
                echo "OK"
        fi
        ;;
  stop)
        echo "Stopping Bluetooth"
        start-stop-daemon -K -q -p /var/run/bluetoothcontrollers.pid --exec /recalbox/scripts/bluetoothcontrollers.sh
        start-stop-daemon -K -q -p /var/run/bluetoothd.pid --exec /usr/libexec/bluetooth/bluetoothd
        echo "OK"
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


